import os
import torch
import torch.nn as nn
from tqdm import tqdm
from model import SpikingNet
from utils_ledger import load_ledger, get_latest_commit, append_commit
from dataset import get_dataloaders

import warnings
warnings.filterwarnings("ignore", category=UserWarning, module="torchaudio")

# --- SETUP ---
# Point this to the folder generated by 0_init.py
TARGET_FOLDER = "experiments/0825_1432_dense_teacher"
EPOCHS_TO_RUN = 100
# -------------

def main():
    device = torch.device("cpu")
    
    # 1. Load the Ledger and State
    ledger = load_ledger(TARGET_FOLDER)
    config = ledger["base_config"]
    latest_commit = get_latest_commit(TARGET_FOLDER)
    
    if not latest_commit:
        raise ValueError("No commits found in the ledger!")
        
    print(f"\n=== Running Training Pipeline ===")
    print(f"Targeting: {TARGET_FOLDER}")
    print(f"Loaded Commit {latest_commit['commit_id']} -> {latest_commit['model_file']}")
    
    # 2. Initialize Model and Load Weights
    model = SpikingNet(
        n_mels=config["n_mels"],
        num_hidden=config["num_hidden"],
        num_outputs=config["num_outputs"],
        beta=config["beta"]
    ).to(device)
    
    model_path = os.path.join(TARGET_FOLDER, latest_commit["model_file"])
    model.load_state_dict(torch.load(model_path, map_location=device))
    
    optimizer = torch.optim.Adam(model.parameters(), lr=config["lr"])
    ce_loss_fn = nn.CrossEntropyLoss()
    
    # Load dataset using settings from the ledger config
    train_loader, test_loader, labels_map = get_dataloaders(
        config=config,
        data_dir="custom_audio",  # Change if your audio folder is named differently
        test_split_pct=config.get("test_split_pct", 0.2)
    )
    
    idx_zwoi = labels_map.get("zwoi", 1)
    idx_foif = labels_map.get("foif", 4)
    
    idx_zwoi = 1
    idx_foif = 4
    
    # 3. The Training Loop
    start_epoch = 0 # If you want cumulative epochs, you can parse this from the ledger
    epoch_history = []
    
    for epoch in range(EPOCHS_TO_RUN):
        model.train()
        total_loss, correct, total = 0, 0, 0
        
        pbar = tqdm(train_loader, desc=f"Epoch {epoch+1:03d}/{EPOCHS_TO_RUN}", leave=False)
        
        for x, y in pbar:
            x, y = x.to(device), y.to(device)
            optimizer.zero_grad()
            
            spk_out = model(x)
            spike_counts = spk_out.sum(dim=1)

            # A. Base CrossEntropy
            ce_loss = ce_loss_fn(spike_counts, y)

            # B. Target Spike Activity Regularization
            target_counts = torch.zeros_like(spike_counts)
            target_counts.scatter_(1, y.unsqueeze(1), config["target_spikes"])
            reg_loss = nn.functional.mse_loss(spike_counts, target_counts)

            # C. Targeted Pairwise Confusion Penalty (foif <-> zwoi)
            spikes_zwoi = spike_counts[:, idx_zwoi]
            spikes_foif = spike_counts[:, idx_foif]
            is_foif = (y == idx_foif).float()
            is_zwoi = (y == idx_zwoi).float()
            conf_loss = torch.mean((spikes_zwoi * is_foif)**2 + (spikes_foif * is_zwoi)**2)

            # D. The Wire Cutter (L1 Penalty)
            # This mathematically forces unused weights toward 0.0
            l1_loss = torch.norm(model.fc1.weight, p=1) + torch.norm(model.fc2.weight, p=1)

            # Total Loss
            loss = ce_loss + (config["lambda_reg"] * reg_loss) + \
                   (config["lambda_confusion"] * conf_loss) + \
                   (config["lambda_l1"] * l1_loss)
                   
            loss.backward()
            optimizer.step()

            total_loss += loss.item()
            correct += (spike_counts.argmax(dim=1) == y).sum().item()
            total += y.size(0)
            
            pbar.set_postfix({"Loss": f"{loss.item():.3f}", "Acc": f"{(correct/total)*100:.1f}%"})

        # 4. Evaluation Loop (Test Loss & Accuracy)
        model.eval()
        val_correct, val_total, val_loss_sum = 0, 0, 0.0
        with torch.no_grad():
            for x, y in test_loader:
                x, y = x.to(device), y.to(device)
                spk_out = model(x)
                spike_counts = spk_out.sum(dim=1)
                
                # Test Loss identical to Train Loss
                ce_loss = ce_loss_fn(spike_counts, y)
                
                target_counts = torch.zeros_like(spike_counts)
                target_counts.scatter_(1, y.unsqueeze(1), config["target_spikes"])
                reg_loss = nn.functional.mse_loss(spike_counts, target_counts)
                
                spikes_zwoi = spike_counts[:, idx_zwoi]
                spikes_foif = spike_counts[:, idx_foif]
                is_foif = (y == idx_foif).float()
                is_zwoi = (y == idx_zwoi).float()
                conf_loss = torch.mean((spikes_zwoi * is_foif)**2 + (spikes_foif * is_zwoi)**2)

                l1_loss = torch.norm(model.fc1.weight, p=1) + torch.norm(model.fc2.weight, p=1)
                
                loss = ce_loss + (config["lambda_reg"] * reg_loss) + (config["lambda_confusion"] * conf_loss) + (config["lambda_l1"] * l1_loss)
                val_loss_sum += loss.item()

                val_correct += (spike_counts.argmax(dim=1) == y).sum().item()
                val_total += y.size(0)
                
        train_acc = (correct / total) * 100
        test_acc = (val_correct / val_total) * 100
        avg_train_loss = total_loss / len(train_loader)
        avg_test_loss = val_loss_sum / len(test_loader)
        
        epoch_history.append({
            "epoch": epoch + 1,
            "train_loss": round(avg_train_loss, 4),
            "test_loss": round(avg_test_loss, 4),
            "train_acc": round(train_acc, 2),
            "test_acc": round(test_acc, 2)
        })

        if (epoch + 1) % 10 == 0 or epoch == EPOCHS_TO_RUN - 1:
            print(f"Epoch {epoch+1:03d}/{EPOCHS_TO_RUN} -> Train: {train_acc:5.1f}% | Test: {test_acc:5.1f}% | Train Loss: {avg_train_loss:.3f} | Test Loss: {avg_test_loss:.3f}")

    # 5. Save the New Commit
    next_id = f"{int(latest_commit['commit_id']) + 1:02d}"
    new_model_filename = f"model_{next_id}_train.pth"
    torch.save(model.state_dict(), os.path.join(TARGET_FOLDER, new_model_filename))
    
    append_commit(
        folder_path=TARGET_FOLDER,
        action="train",
        model_filename=new_model_filename,
        metrics={"test_acc": test_acc, "test_loss": avg_test_loss}, # type: ignore
        extra_data={"epochs_run": EPOCHS_TO_RUN, "history": epoch_history}
    )
    
    print(f"\n>>> Saved new model state as {new_model_filename}")
    print(f">>> Committed to ledger.json")

if __name__ == "__main__":
    main()